Quick build now tests both 64 and 32

diff --git a/build b/build
--- a/build
+++ b/build
@@ -28,12 +28,22 @@ shift
 cd "$(dirname "$0")"
 
 case $cmd in
-  q*) t g++ "${t_gcc_debug_opts[@]}" -DQUICK=1 t/test.cc -o t/test-quick -lboost_context
-      if valgrind --track-origins=yes t/test-quick > t/test-quick.log; then
-        echo -e "\033[1;32mall ok\033[0;0m"
+  q*) t g++                "${t_gcc_debug_opts[@]}" -DQUICK=1      t/test.cc -o t/test-quick -lboost_context
+      t i686-linux-gnu-g++ "${t_gcc_debug_opts[@]}" -DQUICK=1 -m32 t/test.cc -o t/test32-quick
+
+      if valgrind --track-origins=yes t/test-quick 2>&1 >t/test-quick.log; then
+        echo -e "\033[1;32m64-bit all ok\033[0;0m"
       else
         echo -e "\033[1;31merror\033[0;0m"
         less t/test-quick.log
+        exit 1
+      fi
+
+      if valgrind --track-origins=yes t/test32-quick 2>&1 >t/test32-quick.log; then
+        echo -e "\033[1;32m32-bit all ok\033[0;0m"
+      else
+        echo -e "\033[1;31merror\033[0;0m"
+        less t/test32-quick.log
         exit 1
       fi
       ;;
